events {}

http {

  server {
    listen 80;  # ⚠️ Tetap 80 di dalam container (tidak perlu diubah)
                # Karena port mapping diatur di docker-compose (8081:80)

    # GeoServer
    location /geoserver/ {
      proxy_pass http://geoserver:8080/geoserver/;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;

      add_header Access-Control-Allow-Origin *;
      add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
      add_header Access-Control-Allow-Headers "*";

      if ($request_method = OPTIONS) {
        return 204;
      }
    }


    # GeoNode
    location /geonode/ {
      proxy_pass http://geonode:8000/;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }


    # Redirect root ke geonode
    location = / {
      return 302 /geonode/;
    }

  }

}